name: Metrics

on:
  schedule: 
    - cron: "0 0 * * *"
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: spencergoldberg1
          template: classic
          base: header, activity, community, repositories, metadata
